apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: redis-stream-demo
data:
  ASPNETCORE_ENVIRONMENT: "Production"
  Logging__LogLevel__Default: "Information"
  Logging__LogLevel__Microsoft.AspNetCore: "Warning"
  ConnectionStrings__Redis: "redis:6379"
  ASPNETCORE_URLS: "http://+:8080"
